#ifndef __TINY_FS_ERRNO_H__
#define __TINY_FS_ERRNO_H__

#define INVLD_BLK_SIZE -1 
#define DISK_ERROR -2
#define DISK_READ_ERROR -3
#define MOUNTED_ERROR -4
#define MAGIC_NUMBER_ERROR -5
#define WRITE_ERROR -6
#define SEEK_ERROR -7
#define BITMAP_SIZE_ERROR -8
#define SEEK_FAIL -9
#define FREE_BLOCK_ERROR -10
#define FILE_NOT_FOUND_ERROR -11
#define END_OF_FILE_ERROR -12
#define READ_ERROR -13
#define NAME_LENGTH_ERROR -14
#define MKFS_SUCCESS 1
#define MOUNT_SUCCESS 2
#define UNMOUNT_SUCCESS 3
#define READDIR_SUCCESS 4
#define RENAME_SUCCESS 5
#define INFO_SUCCESS 6
#define SEEK_SUCCESS 7
#define READ_SUCCESS 8
#define DELETE_SUCCESS 9
#define WRITE_SUCCESS 10


#endif 
